version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=auth_db

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
      
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    depends_on:
      - backend
